#!/bin/bash
##################################################################################
#       Alexandr Kochenkov     CSE224 Section B
#     Proffesor: Nick Macias      
#    Sorts out the text put in and then tallys the phrases
#
#
##################################################################################

 declare -A tally  #declaring the array
while read line
  do
    line=$(echo $line | tr 'a-z' 'A-Z' | tr '()[]{}"' '@' | tr "'" '@' | sed 's/@//g' | sed 's/[ ][ ]*/ /g' | sed 's/[	][	]*/ /g')
    line=$(echo $line | sed 's/[ ][ ]*/_/g'| sed 's/[_]*[.,;:?!][_]*/ /g')
    for phrase in $line
    do
      val=${tally["$phrase"]}
      val=$((val+1))
      tally["$phrase"]=$val
      #((tally"[$phrase]"+=1))
    done
  done
  for phrase in ${!tally[@]}
  do
    echo ${tally[$phrase]}" "$phrase | tr '_' ' '
  done
